app:
    cors:
        allowedOrigins: http://localhost:3000 # Comma separated list of allowed origins
        maxAgeSeconds: 3600
spring:
    datasource:
        url: jdbc:h2:file:/data/demo
        username: admin
        password: admin
        driverClassName: org.h2.Driver
    security:
        oauth2:
            client:
                registration:
                    VK:
                        client-id: ${VK.client-id}
                        client-secret: ${VK.client-secret}
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/login/oauth2/code/vk
                        scope:
                            - email
                provider:
                    VK:
                        authorization-uri: https://oauth.vk.com/authorize
                        token-uri: https://oauth.vk.com/access_token
                        user-info-uri: https://api.vk.com/method/users.get?v=5.131&fields=photo_max
                        user-name-attribute: first_name
    devtools:
        restart:
            enabled: false
logging:
    level:
        root: info