app:
    protocol: ${SERVER_PROTOCOL:http}
    host: ${SERVER_HOST:localhost}
    port: ${SERVER_PORT:8080}
    address: ${app.protocol}://${app.host}:${app.port}
    hostingAddress: ${SERVER_HOSTING_ADDRESS:${app.address}}
    cors:
        allowedOrigins: ${app.protocol}://${app.host}:3000 # Comma separated list of allowed origins
        maxAgeSeconds: 3600
spring:
    jpa:
      hibernate:
          ddl-auto: update
    datasource:
        url: jdbc:postgresql://${app.host}:5432/encryption
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
    #        url: jdbc:h2:file:/data/demo
#        username: admin
#        password: admin
#        driverClassName: org.h2.Driver
    config:
        import:
            - classpath:application-tokens.yml
    security:
        oauth2:
            client:
                registration:
                    VK:
                        client-id: ${VK.client-id}
                        client-secret: ${VK.client-secret}
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        redirect-uri: ${app.hostingAddress}/login/oauth2/code/vk
                        scope:
                            - email
                provider:
                    VK:
                        authorization-uri: https://oauth.vk.com/authorize
                        token-uri: https://oauth.vk.com/access_token
                        user-info-uri: https://api.vk.com/method/users.get?v=5.131&fields=photo_max
                        user-name-attribute: first_name
    devtools:
        restart:
            enabled: false
logging:
    level:
        root: info
management:
    endpoints:
        web:
            exposure:
                include: health, info, env, beans, heapdump, loggers, metrics, prometheus
    endpoint:
        health:
            enabled: true
            show-details: always
        info:
            enabled: true
        env:
            show-values: always
        beans:
            enabled: true
        heapdump:
            enabled: true
        loggers:
            enabled: true
        metrics:
            enabled: true
    info:
        env:
            enabled: true
        git:
            enabled: true
            mode: full
        build:
            enabled: true
        java:
            enabled: true
    metrics:
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
    prometheus:
        metrics:
            export:
                enabled: true