app:
    protocol: ${SERVER_PROTOCOL:http}
    host: ${SERVER_HOST:localhost}
    port: ${SERVER_PORT:8080}
    address: ${app.protocol}://${app.host}:${app.port}
    cors:
        allowedOrigins: ${app.protocol}://${app.host}:3000 # Comma separated list of allowed origins
        maxAgeSeconds: 3600
spring:
    jpa:
      hibernate:
          ddl-auto: update
    datasource:
        url: jdbc:h2:file:/data/demo
        username: admin
        password: admin
        driverClassName: org.h2.Driver
    config:
        import:
            - classpath:application-tokens.yml
    security:
        oauth2:
            client:
                registration:
                    VK:
                        client-id: ${VK.client-id}
                        client-secret: ${VK.client-secret}
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        redirect-uri: ${app.address}/login/oauth2/code/vk
                        scope:
                            - email
                provider:
                    VK:
                        authorization-uri: https://oauth.vk.com/authorize
                        token-uri: https://oauth.vk.com/access_token
                        user-info-uri: https://api.vk.com/method/users.get?v=5.131&fields=photo_max
                        user-name-attribute: first_name
    devtools:
        restart:
            enabled: false
logging:
    level:
        root: info